export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GETTING_TASKS = 'GETTING_TASKS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';

export const EDITING_TASK = 'EDITING_TASK';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';